site_name: Pydantic Logfire
site_description: Logfire
strict: true
site_url: https://logfire.dev/

# TODO(Marcelo): Uncomment the following when the package gets its own repository.
# repo_name: pydantic/logfire
# repo_url: https://github.com/pydantic/logfire
# edit_uri: edit/main/docs/

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    # - navigation.sections
    - navigation.tabs
  # logo: 'logo-white.svg'
  # favicon: 'favicon.png'

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Get Started:
      - Home: index.md
      - Installation: install.md
      - Configuration: configuration.md
      - Auto Tracing: auto_tracing.md
      - Advanced:
          - Backfill: advanced/backfill.md
          - Sampling: advanced/sampling.md
      - Testing: testing.md
  - Integrations:
      - Integrations: integrations/index.md
      - Pydantic: integrations/pydantic.md
      - FastAPI: integrations/fastapi.md
      - Django: integrations/django.md
      - Flask: integrations/flask.md
      - Starlette: integrations/starlette.md
      - HTTPX: integrations/httpx.md
      - AIOHTTP: integrations/aiohttp.md
      - Requests: integrations/requests.md
      - PyMongo: integrations/pymongo.md
      - Psycopg2: integrations/psycopg2.md
      - Celery: integrations/celery.md
      - Redis: integrations/redis.md
      - SQLAlchemy: integrations/sqlalchemy.md
      - Logging: integrations/logging.md
      - ASGI: integrations/asgi.md
      - WSGI: integrations/wsgi.md
  - Examples:
      - Image Transformation: examples/image_transformation.md
      - FastAPI Application: examples/fastapi.md
      - Web Scraper: examples/web_scraper.md
      - Machine Learning: examples/machine_learning.md
  - API Documentation:
      - Logfire: api/logfire.md
      - Testing: api/testing.md
      - Backfill: api/backfill.md
      - Propagate: api/propagate.md
      - Dash: api/dash.md
      - Exceptions: api/exceptions.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - glightbox
  - mkdocstrings:
      handlers:
        python:
          paths: [src/packages/logfire/logfire]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
hooks:
  - docs/plugins/main.py
