site_name: Pydantic Logfire Documentation
site_description: Pydantic Logfire Documentation
strict: true
site_url: https://docs.logfire.dev

# TODO(Marcelo): Uncomment the following when the package gets its own repository.
# repo_name: pydantic/logfire
# repo_url: https://github.com/pydantic/logfire
# edit_uri: edit/main/docs/

# we have this so the source.html partial is displayed
repo_url: http://for-login-button

theme:
  name: "material"
  custom_dir: "docs/overrides"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.indexes
    - navigation.path
    - navigation.tabs
  logo: "logo-white.svg"
  favicon: "favicon.png"

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

extra_css:
  - "extra/tweaks.css"

# used for analytics
extra_javascript:
  - "/flarelytics/client.js"

nav:
  - Intro: index.md
  - Guide:
      - First Steps: guide/first_steps.md
      - Tracing: guide/tracing.md
      - Metrics: guide/metrics.md
      - Configuration: guide/configuration.md
      - Integrations:
          - Integrations: guide/integrations/index.md
          - Pydantic: guide/integrations/pydantic.md
          - FastAPI: guide/integrations/fastapi.md
          - Django: guide/integrations/django.md
          - Flask: guide/integrations/flask.md
          - Starlette: guide/integrations/starlette.md
          - HTTPX: guide/integrations/httpx.md
          - AIOHTTP: guide/integrations/aiohttp.md
          - Requests: guide/integrations/requests.md
          - PyMongo: guide/integrations/pymongo.md
          - Psycopg2: guide/integrations/psycopg2.md
          - Celery: guide/integrations/celery.md
          - Redis: guide/integrations/redis.md
          - SQLAlchemy: guide/integrations/sqlalchemy.md
          - Logging: guide/integrations/logging.md
          - ASGI: guide/integrations/asgi.md
          - WSGI: guide/integrations/wsgi.md
      - Auto Tracing: guide/auto_tracing.md
      - Dashboard: guide/dashboard.md
      - SQL Explorer: guide/sql_explorer.md
      # - Direct Connection: guide/direct_connection.md
      - Sampling: guide/sampling.md
      # - Data Scrubbing: guide/data_scrubbing.md
      - Backfill: guide/backfill.md
      - Testing: guide/testing.md
      - Organization Structure: guide/organization_structure.md
  - SDK API:
      - Logfire: api/logfire.md
      - Testing: api/testing.md
      - Backfill: api/backfill.md
      - Propagate: api/propagate.md
      - Exceptions: api/exceptions.md
      - Integrations:
          - api/integrations/pydantic_plugin.md
          - api/integrations/logging.md
  - Help: help.md
  - Roadmap: roadmap.md
  - Legal:
      - Terms of Service: legal/terms_of_service.md
      - Privacy Policy: legal/privacy.md
      - Service Level Agreement: legal/service_level_agreement.md
      - Data Processing Addendum: legal/data_processing_addendum.md
      - Cloud Subprocessors: legal/cloud_subprocessors.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
      # this only affects `/legal/` since (at time of change) there are no `h5` in the rest of the docs
      toc_depth: 4
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

watch:
  - logfire

plugins:
  - search
  - glightbox
  - mkdocstrings:
      handlers:
        python:
          paths: [src/packages/logfire/logfire]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            parameter_headings: true
            show_signature_annotations: true
            signature_crossrefs: true
          import:
            - url: https://docs.python.org/3/objects.inv
            - url: https://docs.pydantic.dev/latest/objects.inv
            - url: https://fastapi.tiangolo.com/objects.inv
            - url: https://opentelemetry-python-contrib.readthedocs.io/en/latest/objects.inv
            - url: https://opentelemetry-python.readthedocs.io/en/latest/objects.inv
            - url: https://requests.readthedocs.io/en/latest/objects.inv
            - url: https://typing-extensions.readthedocs.io/en/latest/objects.inv
hooks:
  - docs/plugins/main.py
