[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "logfire/__init__.py"

[project]
name = "logfire"
description = "Coming Soon"
authors = [{ name = "Pydantic Team", email = "hello@pydantic.dev" }]
license = "MIT"
readme = "README.md"
classifiers = [
    "Development Status :: 1 - Planning",
    "Topic :: Internet",
    "Typing :: Typed",
]
requires-python = ">=3.8"
dependencies = [
    # TODO(davidhewitt) - remove these upper bounds once
    # opentelemetry-instrumentation-asgi 0.41b0 is released
    # https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1935
    "opentelemetry-api>=1.19.0,<1.20.0",
    "opentelemetry-sdk>=1.19.0,<1.20.0",
    "opentelemetry-exporter-otlp>=1.19.0,<1.20.0",
    "opentelemetry-instrumentation-asgi>=0.40b0",
    "rich>=13.4.2",
    "structlog>=23.1.0",
    "protobuf>=4.23.4",
    "platformdirs>=3.10.0",
    "pydantic>=2.1.1",
    "pydantic-settings>=2.0.2",
    "typing-extensions",
]
dynamic = ["version"]

[project.entry-points.pydantic]
observer = "logfire.plugin:plugin"
