[project]
name = 'logfire'
description = 'Coming Soon'
authors = [{ name = 'Samuel Colvin', email = 's@muelcolvin.com' }]
license = 'MIT'
readme = 'README.md'
classifiers = [
    'Development Status :: 1 - Planning',
    'Topic :: Internet',
    'Typing :: Typed',
]
requires-python = '>=3.8'
dependencies = [
    'opentelemetry-api>=1.19.0',
    'opentelemetry-sdk>=1.19.0',
    'opentelemetry-exporter-otlp>=1.19.0',
    'rich>=13.4.2',
    'protobuf>=4.23.4',
    'pydantic>=2.1.1',
    "pydantic-settings>=2.0.2",
    "typing_extensions",
]
dynamic = ['version']

[project.entry-points."pydantic"]
observer = 'logfire.plugin:plugin'

[project.optional-dependencies]
dev = ["black", "ruff", "mypy"]

[tool.black]
color = true
line-length = 120
target-version = ['py310']
skip-string-normalization = true

[tool.ruff]
line-length = 120
extend-select = ['Q', 'RUF100', 'C90', 'UP', 'I'] #, 'D', 'T']
# E501 is handled by black
extend-ignore = ['D105', 'D107', 'D205', 'D415', 'E501']
flake8-quotes = { inline-quotes = 'single', multiline-quotes = 'double' }
mccabe = { max-complexity = 14 }
target-version = "py38"
exclude = ['pydantic/v1', 'tests/mypy/outputs']
