[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "logfire/version.py"

[project]
name = "logfire"
description = "Coming Soon"
authors = [{ name = "Pydantic Team", email = "hello@pydantic.dev" }]
license = "MIT"
readme = "README.md"
classifiers = [
    "Development Status :: 1 - Planning",
    "Topic :: Internet",
    "Typing :: Typed",
]
requires-python = ">=3.8"
dependencies = [
    "opentelemetry-api>=1.19.0",
    "opentelemetry-sdk>=1.19.0",
    "opentelemetry-exporter-otlp>=1.19.0",
    "opentelemetry-instrumentation-asgi>=0.40b0",
    "rich>=13.4.2",
    "structlog>=23.1.0",
    "protobuf>=4.23.4",
    "platformdirs>=3.10.0",
    "typing-extensions>=4.0.0",
    "httpx>=0.22.0",
    "psutil>=5.9.5",
]
dynamic = ["version"]

[project.optional-dependencies]
test = []

[project.entry-points.pydantic]
observer = "logfire.plugin:plugin"
