# TODO revert this file to hatchling using https://github.com/pydantic/platform/pull/264/commits/01e4d2258776f98284d019d5040eceeb5e9af42f
# when we move it to a new repo

[tool.poetry]
name = "logfire"
version = "0.5.6"
description = "The observability framework focused on developer experience! 🚀"
authors = ["Pydantic Team <hello@pydantic.dev>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8"
opentelemetry-api = ">=1.19.0"
opentelemetry-sdk = ">=1.19.0"
opentelemetry-exporter-otlp = ">=1.19.0"
rich = ">=13.4.2"
typer = ">=0.9.0"
structlog = ">=23.1.0"
protobuf = ">=4.23.4"
platformdirs = ">=3.10.0"
typing-extensions = ">=4.0.0"
httpx = ">=0.22.0"
psutil = ">=5.9.5"
pydantic = {git = "https://github.com/pydantic/pydantic.git", rev = "50bc0039185c1522174c471bf967fd29a61fce74", optional = true}
# Extras
starlette = {version = ">=0.27.0", optional = true}
dirty-equals = {version = ">=0.6.0", optional = true}
pytest = {version = ">=7.4.2", optional = true}
opentelemetry-instrumentation-asgi = { version = ">=0.40b0", optional = true }
opentelemetry-instrumentation-wsgi = {version = ">=0.40b0", optional = true}
opentelemetry-instrumentation-system-metrics = {version = ">=0.40b0" }

[tool.poetry.extras]
test = ["starlette", "typer", "dirty-equals", "pytest", "pydantic", "opentelemetry-instrumentation-asgi", "opentelemetry-instrumentation-wsgi"]
wsgi = ["opentelemetry-instrumentation-wsgi"]
asgi = ["opentelemetry-instrumentation-asgi"]

[tool.poetry.scripts]
logfire = "logfire.cli:app"

[tool.poetry.plugins."pydantic"]
logfire-plugin = "logfire.integrations.pydantic_plugin:plugin"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
