# TODO revert this file to hatchling using https://github.com/pydantic/platform/pull/264/commits/01e4d2258776f98284d019d5040eceeb5e9af42f
# when we move it to a new repo

[tool.poetry]
name = "logfire"
version = "0.4.0"
description = "The observability framework focused on developer experience! 🚀"
authors = ["Pydantic Team <hello@pydantic.dev>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8"
opentelemetry-api = ">=1.19.0"
opentelemetry-sdk = ">=1.19.0"
opentelemetry-exporter-otlp = ">=1.19.0"
rich = ">=13.4.2"
structlog = ">=23.1.0"
protobuf = ">=4.23.4"
platformdirs = ">=3.10.0"
typing-extensions = ">=4.0.0"
httpx = ">=0.22.0"
psutil = ">=5.9.5"
# Extras
pydantic = {version = ">=2.3", optional = true}
opentelemetry-instrumentation-wsgi = {version = ">=0.40b0", optional = true}
opentelemetry-instrumentation-asgi = {version = ">=0.40b0", optional = true}

[tool.poetry.extras]
all = ["pydantic", "opentelemetry-instrumentation-wsgi", "opentelemetry-instrumentation-asgi"]
backfill = ["pydantic"]
wsgi = ["opentelemetry-instrumentation-wsgi"]
asgi = ["opentelemetry-instrumentation-asgi"]

[tool.poetry.scripts]
logfire = "logfire.cli:app"

[tool.poetry.plugins."pydantic"]
logfire-plugin = "logfire.integrations.pydantic_plugin:plugin"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
