blank_issues_enabled: true
contact_links:
  - name: 💬 Join Slack
    url: 'https://docs.pydantic.dev/logfire/help/#slack'
    about: Join the Pydantic Logfire Slack to ask questions, get help and chat about Logfire
