name: ❓Question
description: As a question about any of Pydantic Logfire
labels: [Question]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: How can we help?
    validations:
      required: true
